# Dockerfile
FROM ufoym/deepo:pytorch

# #Set working directory
# WORKDIR /Volume

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends sudo git vim wget curl unzip && \
#     apt-get install -y libgl1 libglib2.0 git && \
#     rm -rf /var/lib/apt/lists/*

# RUN pip install --upgrade pip && \
#     pip install cython torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113 && \
#    # pip install transformers==4.8.1 timm==0.4.9 wget opencv-python ruamel.yaml salesforce-lavis


# #install COCOAPI
# RUN git clone https://github.com/cocodataset/cocoapi.git
# RUN cd cocoapi/PythonAPI && \
#     make && \
#     cp -r pycocotools /app
# # remove cocoapi
# RUN cd .. && \
#     rm -rf cocoapi
