# train_file: ['data/json_pretrain/coco.json', # 113K - 567K 
#                'data/json_pretrain/vg.json', # 100K - 769K
#                'data/json_pretrain/cc3m_train.json', # 2.95M - 2.95M
#                'data/json_pretrain/cc3m_val.json'
#               #  'data/json_pretrain/sbu.json' #860K  
#                ]
train_file: ['../data/json_pretrain/coco.json',
            '../data/json_pretrain/vg.json',
            '../data/json_pretrain/cc3m_train.json',
            '../data/json_pretrain/cc3m_val.json',
            '../data/json_pretrain/sbu.json'
            ]

bert_config: 'configs/config_bert.json'

image_root: '../data'
image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 128
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4
num_workers: 32

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 30, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 20, cooldown_epochs: 0}

TASK: Pretrain

args:
  checkpoint: ''
  resume: False 
  output_dir: Pretrain/
  text_encoder: 'bert-base-uncased'
  device: cuda
  seed: 42
  world_size: 1
  dist_url: env://
  distributed: True
  evaluate: false

Mixgen:
  num: 0.25

wandb: 
  wandb_use: false