TASK : VE 
train_file: '../data/json_downstream/VE/ve_train.json'
val_file: '../data/json_downstream/VE/ve_dev.json'                
test_file: '../data/json_downstream/VE/ve_test.json'

image_root: '../data/Flickr30K/Images'

batch_size_train: 64
batch_size_test: 128

warm_up: False

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}



romixgen:
  base:
    img_info_json : '../data/json_downstream/VE/romixgen_ve2.json'
    obj_bg_threshold : [0.3,0.6]