TASK : VQA 

args:
  text_decoder: 'bert-base-uncased'
  
train_file: ['../data/json_downstream/vqa_train.json',
             '../data/json_downstream/vqa_val.json',
             '../data/json_downstream/vg_qa.json']
             
test_file: ['../data/json_downstream/vqa_test.json']
answer_list: '../data/json_downstream/answer_list.json'

vqa_root: '../data/COCO/Images' #train2014/
vg_root: '../data/VG/Images'  #image/

image_res: 384
batch_size_train: 2
batch_size_test: 2 
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







